### PR TITLE
Pushover notification service

### PR DESCRIPTION
**Pull request by danialmoghaddam**
Just added Pushover notification service to send out notification when there is a force reboot.

### CODE REVIEW

**Comment by Kasmetski** [comment]
Thank you for the pull request.
I need to make a few changes before commit.
I assume you already tested it?

**Comment by danialmoghaddam** [comment]
@Kasmetski First let me thank you for sharing this application with the community. 

Yes I did some extensive tests and everything is working pretty well.

img_6918

**Comment by Kasmetski** [comment]
Perfect. Can I use this photo for the documentation when I have more time to write it?

I've implemented Telegram remote control but I forgot to push it to github. Now I think to use the Notif() function to send notifications for all implemented services - pushover, telegram (slack soon & etc.)

Thanks again for the commit.

**Comment by danialmoghaddam** [comment]
Absolutely. Feel free to use it if it suits the need. I'll help to push more info on "how to connect the PW switch to the relay". Noobs like me would get confused on NO, NC ports on relay.

**Pull request merged**
